### ISSUE TITLE
Proof of Concept Checklist

### ISSUE THREAD

**Issue by PWKad** [PWKad/litecoin-core-wallet#2]
This is a milestone for the delivery of a proof of concept.  All features should be expected to at least look functional.  

## Contributing

The below tasks outline exactly what needs to be done.  If you are unsure of where to jump in the list below is the exact task list so take the time to get familiar and do not ask questions :)  If the proof of concept proposal is accepted we can take more time to answer questions but for now speed of delivery is key.  

## Links

[Design Documents](https://medium.com/litecoin-foundation/redesigning-litecoin-core-with-lightning-capabilities-3a8ebbea590a) - Has design mock and details the features and general look.
[Litecoin Core](https://github.com/litecoin-project/litecoin) - The core software that runs a Litecoin node.  The proposal is to replace the original wallet included in the software with the Aurelia based web wallet.  The wallet is intended to run on Litecoin core long term but for speed of development *just for the proof of concept* we can use lcoin.
[lcoin](https://github.com/bcoin-org/lcoin) - An alternative implementation of Litecoin core that is geared towards app developers.  For the proof of concept and speed of development the proxy will hit the rest API for lcoin.

## Task List

For the initial proof of concept the following pages / features should be in place - 

 - [ ] Settings Page
  - [ ] Sign Message
  - [ ] Private Keys
  - [ ] Debug
    - [ ] Client information
    - [ ] Peers
 - [ ] Balances Page
  - [ ] My Wallet
    - [ ] Show pending wallet balance
      - [ ] Litecoin Balance
      - [ ] USD Balance (use whichever exchange rate Loafwallet is using if possible)
      - [ ] Show pending amounts
    - [ ] Channels - show zero balances for all and grey out the box (channels are not implemented yet)
 - [ ] Pay Page
    - [ ] Payment details
      - [ ] Show USD equivalent (use same exchange rate from balances / my wallet above)
    - [ ] Confirmation modal
    - [ ] Success modal
 - [ ] Receive Page
    - [ ] Create Payment Request
      - [ ] Display qr code
      - [ ] Display receive address
    - [ ] History
      - [ ] Show last 5 receives
 - [ ] Channels Page
    - [ ] Channel component
      - [ ] Show channel details (who, pay, request)
      - [ ] Create basic graph (random data)
 - [ ] Transactions Page
    - [ ] Transaction list component
      - [ ] Show transactions list

**Comment by PWKad** [comment]
For a list of JSON RPC calls that are available -

https://bitcoin.org/en/developer-reference#remote-procedure-calls-rpcs

**Comment by PWKad** [comment]
If you are looking for some basic direction you can look at the `client-information` route that is set up inside of the `settings` route - `src/routes/settings/routes/client-information' - which shows a complete end to end call of data and displaying it from the Litecoin node.

**Comment by adriatic** [comment]
I saw this thread **only after** writing my comment in Discourse. So, I see that you did a lot more in this task than I anticipated and that appeals to me a lot. So, I am in a bind (assuming that you would care having me as a collaborator on this project) - as I have many open projects (Rob knows abou them all and keeps encouraging me to continue pursuing them even just myself)

**Comment by JuxhinDB** [comment]
If someone would like to shoot me a quick email giving a rundown on how the backend/API development is being done, I could look to implement a few of these features (should I be of any use).

**Comment by PWKad** [comment]
Hey @JuxhinDB I'll try to do here shortly.
